# Generated by Django 4.2.9 on 2024-12-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unicms_unical_storage_handler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webpathcdscod",
            name="cds_cod",
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
